name: "Add New Article"
description: "Submit a new article for IJBMRS"
title: "[New Article]: "
labels: ["article"]
body:
  - type: input
    id: title
    attributes:
      label: Article Title
      placeholder: Enter the article title
    validations:
      required: true

  - type: textarea
    id: authors
    attributes:
      label: Authors
      description: One author per line
    validations:
      required: true

  - type: input
    id: volume
    attributes:
      label: Volume
      placeholder: "01"
    validations:
      required: true

  - type: input
    id: issue
    attributes:
      label: Issue
      placeholder: "01"
    validations:
      required: true

  - type: input
    id: year
    attributes:
      label: Publication Year
      placeholder: "2025"
    validations:
      required: true

  - type: input
    id: doi
    attributes:
      label: DOI (Zenodo)
      placeholder: "10.5281/zenodo.xxxxxxx"
    validations:
      required: true

  - type: input
    id: pdf
    attributes:
      label: PDF URL
      placeholder: "https://files.ijbmrs.org/volume-01/issue-01/article-01.pdf"
    validations:
      required: true
